### ISSUE TITLE
Todo till next update

### ISSUE THREAD

**Issue by budRich** [budlabs/i3ass#83]
I have some things I would like to include in the next update, writing it down so I don't forget. I will try to release the update before 4/20 2021

---

- [x] Multimonitor focusing should work better #5 , #81
- [ ] enable sponsor feature for i3ass
- [ ] Resolve all open issues
  - [ ] #81 
  - [ ] #79 
  - [ ] #77 
  - [ ] #75 
  - [ ] #74 
  - [ ] #72 
  - [ ] #71 
  - [ ] #70 
  - [ ] #66 
  - [ ] #64 
  - [ ] #58 
  - [ ] #57 
  - [ ] #56 
  - [ ] #55 
  - [ ] #53 
  - [ ] #37 
  - [ ] #30 
  - [ ] #27 
  - [ ] #5 
  - [ ] #2 
- [ ] Refactor `i3menu`
  - [ ] fix unreported bug that makes it v e r y  s l o w to load very big lists
- [ ] Stop using i3var and instead store and load variables from cache files
- [ ] Research possibility to do i3fyra without `i3-msg open` (`i3gw`), implement if possible
- [ ] Rewrite i3list in a more efficient language (C or GO) for performance reasons

**Comment by kabeersvohra** [comment]
Hi @budRich, I am so happy to see that this is still being developed on, actually my two main pain points are the multimonitor issue as well as this https://github.com/budlabs/i3ass/issues/84 that I just created. I would really appreciate it if these could both be considered to be included in the next release. I have been using i3viswiz for over a year now and I am so happy with it. Thanks!

**Comment by budRich** [comment]
:D yes i have not given up on i3ass, but I will probably develop on it like i am now, give it a month or two of attention a year (if there isn't anything critical). I looked at your issue, and I will keep it in mind, it's a tough one, it would be a really nice addition.

**Comment by budRich** [comment]
An update on the update:

I have gotten multiple monitors to work well now with **i3viswiz** and **i3list** , I more or less rewrote all the AWK in them from scratch. i3list was actually in much more need of a rewrite..

There was a nasty bug in i3list, that reported wrong workspace numbers if multiple monitors where connected that made most of my scripts (which relies on i3list) to be a bit.. unpredictable, in such setups, but it should be fixed now.

I will decide tomorrow if I try to push an update to i3ass "now" with the changes, but there are some more stuff I would like to include, and I am somewhat in a good mode for doing this, so I think I will do that.

There are some dev branches on i3list, i3viswiz and i3fyra in the i3ass-dev organization on github, if anyone dares to try them out.

**Comment by kabeersvohra** [comment]
Ahhh, amazing work thank you @budRich, can I donate somewhere to thank you for the time you have invested?

**Comment by budRich** [comment]
I will try setting up the sponsors thing for i3ass here on github.

**Comment by kabeersvohra** [comment]
@budRich I am trying to compile the `multimon` branch from i3ass-dev/i3viswiz but I am unsure how to get the single executable to test the multimonitor setup?

**Comment by kabeersvohra** [comment]
hey @budRich, was wondering if you want some help on this, will have some time next week and happy to contribute

**Comment by kabeersvohra** [comment]
hey @budRich, sorry to bother you again, was wondering if any progress was made on this? Eagerly awaiting the update :)

**Comment by budRich** [comment]
@kabeersvohra 
I think I am finally done with the programming for the next version of i3ass. I ended up re-writing i3fyra also (I made a video rant about it earlier today).

Since many of the scripts depend on each other (i3fyra depends on i3viswiz and i3list for instance), i want to release all of them at once.

However, since I know you are particularly interested in i3viswiz, i added the complete script as a gist:  
https://gist.github.com/budRich/3f4108f65f92ecb634f1797fd655119f

See the release notes for changes that has been done:  
https://github.com/i3ass-dev/i3viswiz/blob/dev/releasenotes/2021.05.24.md
(if anyone see this in *the future* and i have forgot to remove the link and or gist, don't use it, use the published version instead)  

But be aware, if you are using other components of i3ass, they will not play nice with this new version of i3viswiz.

---

this is by far the biggest i3ass update I have done, a lot of "under-the-hood" improvements, not so much "new features" beside multimonitor support.

**Comment by kabeersvohra** [comment]
amazing, thank you for all your hard work @budRich. I just tried to use the bash script that you put in the gist now and running `i3viswiz left` is hanging for me in the console right now, it does not have any stdout either. Any steps you would like me to take for debugging?

**Comment by budRich** [comment]
that's strange, it should work. whats the output if you do: `i3viswiz left --verbose`

**Comment by kabeersvohra** [comment]
> that's strange, it should work. whats the output if you do: `i3viswiz left --verbose`
(I named it `i3viswiz_new` for the moment so I can keep using `i3viswiz`)

![Screenshot from 2021-05-26 11-32-20](https://user-images.githubusercontent.com/5859986/119645639-2852b900-be16-11eb-990f-fcb5a344ce96.png)

**Comment by budRich** [comment]
hmm, yeah that's strange, it should never do that. 
what do you get from `gawk --version | head -1` (i have: GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)) .  

Might have something to do with how i pass variables to Awk, it is no big deal to change it in to the legacy way of doing it (-v).

Other things you can test is this command: `i3viswiz --instance --debug ALL` , it should print a list of all visible windows and some additional debug vars:  

```
grouplayout="tabbed" groupid=94130370023600 lastingroup=94130370233200 gap=5 grouppos=1 firstingroup=94130370233200 groupsize=1 
* 94130370233200 ws: 1 x: 0     y: 0     w: 1255  h: 332   | termsmall
- 94130369418608 ws: 1 x: 0     y: 332   w: 1255  h: 721   | vivaldi-stable
- 94130371050896 ws: 1 x: 1255  y: 0     w: 665   h: 539   | gl
- 94130369655280 ws: 1 x: 1255  y: 539   w: 665   h: 514   | irssi
```

**Comment by budRich** [comment]
I just realized i have one recursing function that's where it must get stuck. 
Make sure you don't have any windows with sensitive information (in the window titles) then post the content of `i3-msg -t get_tree` , you could use a secret gist or use a temporary pastebin or simply delete the comment here later.  
And i can test the script with your layout to see whats going on.

**Comment by kabeersvohra** [comment]
`gawk --version | head -1` gives me:

`GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.2.0)`

`i3viswiz_new --instance --debug ALL --verbose` hangs at:

`---i3viswiz start---`

`i3-msg -t get_tree` gives me https://pastebin.com/UF3P0yLs

Thanks a lot for this, let me know if I can help more, would also be willing to jump on a zoom debug later on if you wanted

**Comment by budRich** [comment]
not sure how the output on the pastebin got so mangled, it is supposed to be one single string. I managed to make it into oneline, and get jq to pretty print it, but there are still errors in the json, (space characters that breaks words f.i. "false" -> "fa lse").

Try this: `i3-msg -t get_tree | xclip -selection c` , that should put the output in the clipboard, then just paste that on pastebin again.

But I can see that you are using i3-gaps, I have not tested this against gaps at all, I thought it should work anyways.

I don't think it will be difficult to make this work with gaps, so lets do that.

i3-gaps was recently added to the official arch repositories, so i will install it here and test it myself also.

**Comment by kabeersvohra** [comment]
ah sorry about that, I pasted it again here - https://pastebin.com/3LiFVArx

**Comment by budRich** [comment]
i decided i don't want to support gaps, since i don't use it myself, sorry, i updated all i3ass scripts, new version is on AUR.

**Comment by kabeersvohra** [comment]
> i decided i don't want to support gaps, since i don't use it myself, sorry, i updated all i3ass scripts, new version is on AUR.

thanks @budRich I appreciate that, I think I would prefer not to use gaps and use the latest version of i3viswiz instead so I will find some time next week hopefully to uninstall gaps and use the latest version. Thanks for all your work :)

**Comment by kabeersvohra** [comment]
hi @budRich, I would love to try out the newer version of i3viswiz but I am unable to change from i3 gaps to normal i3 because I am using regolith linux which is tied to i3 gaps and the possibility of using it with normal i3 seems a long time away (if ever). Do you think you would consider trying again to support gaps at some point in the future? it would be much appreciated. Thanks
